# Generated by Django 5.2.4 on 2025-07-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_quotes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('liked_quotes', models.JSONField(default=dict)),
                ('disliked_quotes', models.JSONField(default=dict)),
            ],
        ),
    ]
