# Generated by Django 5.2.4 on 2025-07-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_list',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_quotes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='watched_quotes',
            field=models.JSONField(default=dict),
        ),
    ]
