# Generated by Django 5.2.4 on 2025-07-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_disliked_list_user_ip_address_user_liked_quotes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='disliked_list',
            new_name='disliked_quotes',
        ),
    ]
