# Generated by Django 5.2.4 on 2025-07-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_disliked_list_user_disliked_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disliked_quotes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked_quotes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watched_quotes',
        ),
    ]
