# Generated by Django 5.2.4 on 2025-07-15 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(limit_choices_to=3, on_delete=django.db.models.deletion.CASCADE, to='quotes.source', verbose_name='Источник'),
        ),
    ]
