# Generated by Django 5.2.4 on 2025-07-15 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_quote_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.source', verbose_name='Источник'),
        ),
    ]
